import { StyleSheet, Platform, Dimensions } from 'react-native';

// Create styles for the profile screen
export const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    backgroundImage: {
      position: 'absolute',
      width: '100%',
      height: '100%',
    },
    gradient: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '50%',
    },
    contentContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: 0,
    },
    buttonContainer: {
      width: '100%',
      paddingHorizontal: 30,
      gap: 15,
    },
    primaryButton: {
      backgroundColor: '#cca702',
      borderColor: '#cca702',
      borderRadius: 12,
      paddingVertical: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    primaryButtonText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '600',
    },
    secondaryButton: {
      backgroundColor: '#fff',
      borderRadius: 12,
      paddingVertical: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: '#fff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    secondaryButtonText: {
      color: '#cca702',
      fontSize: 18,
      fontWeight: '600',
    },
    buttonIcon: {
      marginRight: 10,
    },
    
    // Modal Styles
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
      padding: 20,
    },
    modalContent: {
      backgroundColor: '#fff',
      borderRadius: 20,
      padding: 30,
      width: '90%',
      maxHeight: '80%',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      marginBottom: 15,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#f0f0f0',
      alignItems: 'center',
      justifyContent: 'center',
    },
    imagePreviewContainer: {
      width: '100%',
      height: '100%',
      maxHeight: 400,
      marginBottom: 5,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: '#f8f8f8',
      position: 'relative',
    },
    imagePreview: {
      width: '100%',
      height: '100%',
    },
    analyzeButton: {
      backgroundColor: '#cca702',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      marginTop: 10,
    },
    analyzeButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    disabledButton: {
      backgroundColor: '#cccccc',
      opacity: 0.7,
    },
    loadingOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.3)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
      marginTop: 10,
    },
    scanButton: {
      backgroundColor: '#cca702',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 5,
      width: '100%',
    },
    uploadButton: {
      backgroundColor: '#fff',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
      color: 'cca702',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    uploadButtonText: {
      color: '#cca702',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 10,
    },
    buttonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 10,
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    analysisResultContainer: {
      alignItems: 'center',
      marginTop: 20,
    },
    scoreTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
    },
    scoreCircle: {
      width: 40,
      height: 40,
      borderRadius: 40,
      backgroundColor: '#cca702',
      justifyContent: 'center',
      alignItems: 'center',
    },
    scoreText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: 'bold',
    },
    viewDetailsButton: {
      backgroundColor: '#cca702',
      borderRadius: 8,
      marginTop: 20,
      paddingVertical: 15,
      paddingHorizontal: 30,
    },
    viewDetailsText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: 'bold',
    },
  });